# Generated by Django 5.0.1 on 2024-03-19 09:20

import datetime
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_type', models.PositiveIntegerField(default=1, help_text='1: Chi tiền, 2: Thu tiền, ...')),
                ('ca_name', models.CharField(default='', max_length=100)),
                ('ca_image', models.ImageField(default=None, upload_to='images')),
                ('ca_explanation', models.CharField(default='', max_length=1000)),
                ('ca_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('ca_created_date', models.DateTimeField(auto_now_add=True)),
                ('ca_modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='helpInformation',
            fields=[
                ('id_hvsi', models.BigAutoField(primary_key=True, serialize=False)),
                ('HDSD', models.TextField()),
                ('website', models.URLField()),
                ('followFB', models.URLField()),
                ('shareFB', models.URLField()),
                ('usageA', models.TextField()),
                ('PAP', models.TextField()),
            ],
            options={
                'db_table': 'helpInformation',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('type', models.PositiveIntegerField(choices=[(1, 'User'), (2, 'Admin')], default=1)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('mobile_code', models.CharField(default='', max_length=6)),
                ('password', models.CharField(default='', max_length=100)),
                ('access_token', models.CharField(default='', max_length=255)),
                ('refresh_token', models.CharField(default='', max_length=255)),
                ('access_token_expiration', models.DateTimeField(auto_now_add=True)),
                ('refresh_token_expiration', models.DateTimeField(auto_now_add=True)),
                ('reset_code', models.CharField(default='0000', max_length=6)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('ac_name', models.CharField(default='', max_length=100)),
                ('ac_money', models.IntegerField(default=0)),
                ('ac_type', models.PositiveIntegerField(default=1, help_text='1: Tiền mặt, 2: Tài khoản ngân hàng, ...')),
                ('ac_explanation', models.CharField(default='', max_length=1000)),
                ('ac_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('ac_created_date', models.DateTimeField(auto_now_add=True)),
                ('ac_modify_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('category_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('cad_type', models.PositiveIntegerField(default=1, help_text='1: Chi tiền, 2: Thu tiền, ...')),
                ('cad_name', models.CharField(default='', max_length=100)),
                ('cad_image', models.ImageField(default=None, upload_to='images')),
                ('cad_explanation', models.CharField(default='', max_length=1000)),
                ('cad_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('cad_created_date', models.DateTimeField(auto_now_add=True)),
                ('cad_modify_date', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'db_table': 'CategoryDetails',
            },
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id_n', models.BigAutoField(primary_key=True, serialize=False)),
                ('text_n', models.TextField()),
                ('read_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_type', models.PositiveIntegerField(default=1, help_text='1: Chi tiền, 2: Thu tiền, ...')),
                ('p_money', models.IntegerField(default=0)),
                ('p_explanation', models.CharField(default='', max_length=1000)),
                ('p_date', models.DateField(default=datetime.date.today)),
                ('p_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('p_created_date', models.DateTimeField(auto_now_add=True)),
                ('p_modify_date', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('category_details_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.categorydetails')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Pay',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(default='', max_length=100)),
                ('u_image', models.ImageField(default=None, upload_to='images')),
                ('u_gender', models.PositiveIntegerField(default=1, help_text='1: Nam, 2: Nữ, ...')),
                ('u_birthday', models.DateField(default=datetime.date.today)),
                ('u_address', models.CharField(default='', max_length=200)),
                ('u_job', models.CharField(default='', max_length=100)),
                ('u_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('u_created_date', models.DateTimeField(auto_now_add=True)),
                ('u_modify_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
